# Generated by Django 3.2.23 on 2024-02-11 02:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_alter_receita_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='data',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
