# Generated by Django 3.2.23 on 2024-02-11 23:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_alter_despesa_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 11, 23, 48, 21, 132300, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='receita',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 11, 23, 48, 21, 132300, tzinfo=utc)),
        ),
    ]
