# Generated by Django 3.2.23 on 2024-02-11 23:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_auto_20240211_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='receita',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
