# Generated by Django 3.2.23 on 2024-02-12 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0005_auto_20240211_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='categoria',
            field=models.CharField(choices=[('alimentação', 'alimentação'), ('saúde', 'saúde'), ('moradia', 'moradia'), ('transporte', 'transporte'), ('educação', 'educação'), ('lazer', 'lazer'), ('imprevistos', 'imprevistos'), ('outras', 'outras')], default='outras', max_length=20),
        ),
        migrations.AddField(
            model_name='receita',
            name='categoria',
            field=models.CharField(choices=[('alimentação', 'alimentação'), ('saúde', 'saúde'), ('moradia', 'moradia'), ('transporte', 'transporte'), ('educação', 'educação'), ('lazer', 'lazer'), ('imprevistos', 'imprevistos'), ('outras', 'outras')], default='outras', max_length=20),
        ),
    ]
