# Generated by Django 3.2.23 on 2024-02-12 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0006_auto_20240211_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='categoria',
            field=models.CharField(choices=[('alimentação', 'alimentação'), ('saúde', 'saúde'), ('moradia', 'moradia'), ('transporte', 'transporte'), ('educação', 'educação'), ('lazer', 'lazer'), ('imprevistos', 'imprevistos'), ('outras', 'outras')], max_length=20),
        ),
    ]
