# Generated by Django 3.2.23 on 2024-02-12 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0007_alter_receita_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='categoria',
        ),
    ]
