# Generated by Django 3.2.23 on 2024-02-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0008_remove_receita_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('valor_total_despesas', models.DecimalField(decimal_places=2, max_digits=8)),
                ('saldo_final', models.DecimalField(decimal_places=2, max_digits=8)),
                ('valor_gasto_por_categoria', models.TextField()),
            ],
        ),
    ]
