# Generated by Django 3.2.23 on 2024-02-20 11:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0009_resumo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumo',
            old_name='valor',
            new_name='valor_total_receitas',
        ),
        migrations.AddField(
            model_name='resumo',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
