# Generated by Django 3.2.23 on 2024-02-24 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0010_auto_20240220_0830'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resumo',
        ),
    ]
